# Dockerfile for building React app
FROM node:17-alpine AS build

# Set working directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
RUN npm install 

# Add app
COPY . ./

# Build the app
RUN npm run build
