# Dockerfile for building React app
FROM node:17-alpine AS build

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json ./
RUN npm install 

# add app
COPY . ./

# build the app
RUN npm run build
