# Stage 1: Build the React app
FROM node:17-alpine AS build

# Set working directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
RUN npm install 

# Add app source
COPY . ./

# Build the app
RUN npm run build

# Stage 2: Serve the app with Nginx
FROM nginx:alpine

# Copy the build output to replace the default Nginx HTML
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
